version: "3.9"
services:
  database:
    container_name: database
    image: mongo:4
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: diana
      MONGO_INITDB_ROOT_PASSWORD: supersecurepassword
      MONGO_INITDB_DATABASE: XeoSmartHome
    volumes:
      - ~/mongo/data:/data/db
  api:
    container_name: api
    build:
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - database
    environment:
      - DATABASE_URI=mongodb://diana:supersecurepassword@database:27017
      - PORT=80
