on:
  push:
    branches:
      - master
jobs:
  deploy-to-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to server
        run: docker-compose up -d --build
